/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prjrx.telas;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import br.com.prjrx.dal.ConexaoBd;
import javax.swing.JOptionPane;
//importar a telafilme para setar no campo de texto os filmes do BD.
import br.com.prjrx.telas.TelaFilme;

/**
 *
 * @author Alexandre
 */
public class TelaSala extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaSala
     */
    public TelaSala() {
        initComponents();
        conexao = ConexaoBd.conector();
    }
    
    private void adicionaSala(){
        String sql = "insert into gcsalas values(?,?,?)" ;
        
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSalaCod.getText());
            pst.setString(2, txtSalaCap.getText());
            pst.setString(3, txtSalaExib.getText());
            if((txtSalaCod.getText().isEmpty()) || txtSalaCap.getText().isEmpty() 
                    || txtSalaExib.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null, "Preencha todos os campo obrigatórios!");
                
            }else{
                int adiciona = pst.executeUpdate();
                if(adiciona > 0){
                    JOptionPane.showMessageDialog(null, "Sala Cadastrada com Sucesso!");
                    txtSalaCod.setText(null);
                    txtSalaCap.setText(null);
                    txtSalaExib.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void excluirSala(){
        int confirma = JOptionPane.showConfirmDialog(null,
                 "Tem certeza que deseja remover esta Sala?",
                 "Atenção!", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            String sql = "delete from gcsalas where codigo = ?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtSalaCod.getText());
                int apagado= pst.executeUpdate();
                if(apagado > 0){
                    JOptionPane.showMessageDialog(null,
                             "Sala removida com sucesso!");
                    txtSalaCod.setText(null);
                    txtSalaCap.setText(null);
                    txtSalaExib.setText(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    private void exibirFilmes(){
        String sql = "select * from gcsalas where codigo = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSalaCod.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                txtSalaExib.setText(rs.getString(3));
                
            } else{
                JOptionPane.showMessageDialog(null
                        , "Por favor,insira o Código da Sala corretamente!");
                txtSalaCod.setText(null);
                txtSalaCap.setText(null);
                txtSalaExib.setText(null);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSalaCod = new javax.swing.JTextField();
        txtSalaCap = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalaExib = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnSalaDel = new javax.swing.JButton();
        btnSalaList = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Sala");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(430, 480));

        jLabel1.setText("Código*");

        jLabel2.setText("Capacidade");

        jLabel3.setText("Filme a ser exibido*");

        jLabel4.setText("* Campos Obrigatórios.");

        txtSalaExib.setColumns(20);
        txtSalaExib.setRows(5);
        jScrollPane2.setViewportView(txtSalaExib);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/prjrx/icones/addSala.png"))); // NOI18N
        jButton1.setToolTipText("Adicionar Sala");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(64, 64));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalaDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/prjrx/icones/SalaDelete.png"))); // NOI18N
        btnSalaDel.setToolTipText("Excluir Sala");
        btnSalaDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalaDel.setPreferredSize(new java.awt.Dimension(64, 64));
        btnSalaDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaDelActionPerformed(evt);
            }
        });

        btnSalaList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/prjrx/icones/SalaExib.png"))); // NOI18N
        btnSalaList.setToolTipText("Listar Filmes");
        btnSalaList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalaList.setPreferredSize(new java.awt.Dimension(32, 32));
        btnSalaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnSalaList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalaCod)
                            .addComponent(txtSalaCap, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalaDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSalaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalaCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalaDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalaList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Chamando metodo adicionaSalas
        adicionaSala();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalaDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaDelActionPerformed
        // Chamando metodo removeSala
        excluirSala();
    }//GEN-LAST:event_btnSalaDelActionPerformed

    private void btnSalaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaListActionPerformed
        // Chamando método exibirFilmes.
        exibirFilmes();
    }//GEN-LAST:event_btnSalaListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalaDel;
    private javax.swing.JButton btnSalaList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSalaCap;
    private javax.swing.JTextField txtSalaCod;
    private javax.swing.JTextArea txtSalaExib;
    // End of variables declaration//GEN-END:variables
}
